# Generated by Django 4.1.2 on 2022-11-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('author', models.CharField(max_length=350)),
                ('publisher', models.URLField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
